#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "reiverr"
name = "Reiverr"
description.en = "Clean combined interface for Jellyfin, TMDB, Radarr and Sonarr, as well as a replacement to Overseerr"
description.fr = "Interface claire combinée pour Jellyfin, TMDB, Radarr et Sonarr, en plus d’être un remplaçant d’Overseerr"

version = "1.1.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/aleksilassila/reiverr"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

 [resources]
  
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/aleksilassila/reiverr/archive/refs/tags/v1.1.1.tar.gz"
        sha256 = "2af462960f4364bde95760c8827aa5cbcb56f9b214e420ca6cef73347d8f1acc"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9494

    [resources.apt]
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

