#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "reiverr"
name = "Reiverr"
description.en = "Clean combined interface for Jellyfin, TMDB, Radarr and Sonarr, as well as a replacement to Overseerr"
description.fr = "Interface claire combinée pour Jellyfin, TMDB, Radarr et Sonarr, en plus d’être un remplaçant d’Overseerr"

version = "0.8.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/aleksilassila/reiverr"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

 [resources]
  
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/aleksilassila/reiverr/archive/refs/tags/v0.8.1.tar.gz"
        sha256 = "3f718a4af54310d545a8423568468a0f772f6fff1a78e3b23c6cb2d2a1fe3f36"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9494

